# Generated by Django 4.2.7 on 2023-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('curso', models.CharField(choices=[('Ads', 'Ads'), ('Eng.Civil', 'Eng.civil'), ('Medicina', 'Medicina'), ('História', 'História'), ('Eng. Aeroespacial', 'Eng. Aeroespacial')], max_length=50)),
                ('periodo', models.CharField(choices=[('1º', '1º'), ('2º', '2º'), ('3º', '3º'), ('4º', '4º'), ('5º', '5º'), ('6º', '6º'), ('7º', '7º'), ('8º', '8º')], max_length=8)),
            ],
        ),
    ]
